#!/bin/bash
#
# edit - Find a file in your $PATH to edit, or if an absolute path
#        is provided, edit that file instead. If a non-existent
#        file is supplied, use that. If nothing is provided,
#        edit a temp file in $TMPDIR.
#        Use $EDITOR if defined, otherwise default back to vi.
#
# Copyright (C) 2026 Michael Davies <michael@the-davies.net>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
# 02111-1307, USA.
#

command -v bashlib.sh &> /dev/null || \
{ echo >&2 "$(basename $0): Can't find bashlib.sh.  Aborting."; exit 1; }
. bashlib.sh

EDITOR="${EDITOR:-vi}"
TMPDIR="${TMPDIR:-/tmp}"
FILENAME=$1

if is_available $1 ; then
  FILENAME=$(which $1)
elif [ -z "$1" ] ; then
  FILENAME="$(mktemp ${TMPDIR}/foo.XXXXXXXXX)"
fi

${EDITOR} $FILENAME
