#!/usr/bin/bash
#
# netspeed - simple network speed display tool
#            Adapted from a twitter post
#            https://twitter.com/gubatron/status/1176250852119461888
#
#            There's a helpful bash completion script that helps out over here:
#            https://github.com/mrda/junkcode/blob/master/bash_completion.d/netspeed.bash_completion
#
# Copyright (C) 2019 Michael Davies <michael@the-davies.net>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
# 02111-1307, USA.
#
BASENAME=$(basename $0)
IFACE=$1

if [[ "$#" -ne 1 ]]; then
  printf "Usage: %s <network-interface>\n" $BASENAME
  exit 2
fi

if [[ ! -e /sys/class/net/$IFACE ]]; then
  printf "%s: Unknown network interface '%s'. Exiting...\n" $BASENAME $IFACE
  exit 3
fi

echo "^C to exit..."
while true; do
    TX1=$(cat /sys/class/net/${IFACE}/statistics/tx_bytes)
    RX1=$(cat /sys/class/net/${IFACE}/statistics/rx_bytes)
    sleep 1
    TX2=$(cat /sys/class/net/${IFACE}/statistics/tx_bytes)
    RX2=$(cat /sys/class/net/${IFACE}/statistics/rx_bytes)
    TBPS=$(expr $TX2 - $TX1)
    RBPS=$(expr $RX2 - $RX1)
    TKBPS=$(expr $TBPS / 1024)
    RKBPS=$(expr $RBPS / 1024)
    echo "iface: $IFACE tx: $TKBPS kb/s rx: $RKBPS kb/s"
done
