#!/bin/bash
#
# noauth-local-ironic - execute the python-ironicclient command against a
#                       running ironic server, defaulting to localhost,
#                       using noauth, taking into consideration that
#                       python-ironicclient might have been installed into
#                       a virtualenv created by openstack-ansible-ironic
#
# Copyright (C) 2014 Michael Davies (michael@the-davies.net)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
# 02111-1307, USA.
#
COMMAND=ironic

export OS_AUTH_TOKEN=fake-token
export IRONIC_URL=http://"${IRONIC_HOST:-localhost}":6385/

# See if we have a $COMMAND already
if [ "z$(which x${COMMAND})" != "z" ] ; then
    "${COMMAND}" "$@"
    exit $?  # Exit with return status from $COMMAND
fi

# Rats, we can't find $COMMAND, so try and find a virtualenv
# where $COMMAND might exist
VENVS_TO_TRY=( \
    ${HOME}/.virtualenvs/python-ironicclient \
    /openstack/venvs/ironic-untagged \
    ${HOME}/.virtualenvs/ironic \
    )

for v in "${VENVS_TO_TRY[@]}"
do
    ACTIVATE="${v}/bin/activate"
    if [ -f "${ACTIVATE}" ]; then
        VENV="${ACTIVATE}"
        break
    fi
done

if [ -z "${VENV}" ]; then
    echo "No environment found to run '${COMMAND}'"
    exit 5
fi

# Start the virtualenv
. ${VENV}

"${COMMAND}" "$@"
exit $?
