#!/bin/bash
#
# not - flip the return code on command invocation
#
# Copyright (C) 2020 Michael Davies <michael@the-davies.net>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
# 02111-1307, USA.
#
[[ $# -eq 0 ]] \
    && printf "Usage: $(basename $0) [-q] <command> - flip the return code on command invocation\n" \
    && exit 1

if [[ "$1" == "-q" ]]; then
    ${@:2} &> /dev/null  # allow the output to be squashed with a -q option
else
    $@
fi

[[ $? -eq 0 ]] && exit 1
exit 0  # any return code other than zero will return zero
