#!/bin/sh
#
# remhelp - display help documentation for the remember group of commands
#
# Copyright (C) 2012, 2013.  All Rights Reserved.
# Michael Davies <michael@the-davies.net>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
# 02111-1307, USA.
#
cat << EOF

remember and friends - a really simple TODO list manager

Files
~~~~~
\$HOME/.remember   - the file where your TODO list is kept

Available Commands
~~~~~~~~~~~~~~~~~~

remember <string> - Remember <string> as a task to do later
remhelp           - Display this help documentation
remindedit        - Use \$EDITOR to edit your TODO list
remindme [string] - Display your TODO list, optionally grepping for [string]

EOF

