#!/bin/bash
#
# schedule-coffee-break - Does what it says on the box.  Turns on the coffee
#                         machine, waits for it to warm up, prompts the user
#                         to make a coffee, gives them time to make a coffee,
#                         then turns the machine off again.
#
# Copyright (C) 2019, 2021 Michael Davies <michael@the-davies.net>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# Or try here: http://www.fsf.org/copyleft/gpl.html

#WARM_UP=15   # mins for the Rancillio Silvia
WARM_UP=20   # mins for the Lelit Bianca and other E61 groups
TURN_OFF=10  # mins

# Include bash library
command -v bashlib.sh &> /dev/null || \
{ echo >&2 "$(basename $0): Can't find bashlib.sh.  Aborting."; exit 1; }
. bashlib.sh

ensure_cmd ha
ensure_cmd beep
ensure_cmd play
ensure_cmd timebar
ensure_cmd dialogbox

ha switch.coffee_machine on
timebar $WARM_UP "Warming up coffee machine for"

beep
if [ -r ${HOME}/sounds/coffee-time.mp3 ]; then
    play -q ${HOME}/sounds/coffee-time.mp3
fi
dialogbox "Serious Cybernetics Corporation" "It\'s time for a coffee break\!"

timebar $TURN_OFF "Turning off coffee machine in"
ha switch.coffee_machine off
