---
#
# Ensure required variables are set
# How to test: ansible-playbook pre-flight-check.yml --extra-vars "foo=1 bar='hello' baz=true"
#
# Copyright (C) 2015 Michael Davies <michael@the-davies.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
- name: Pre flight check TC
  hosts: localhost
  tasks:
    - name: Pre flight check
      fail:
        msg: "Mandatory variable '{{ item }}' is missing"
      when: vars[item] is not defined
      with_items:
        - foo
        - bar
        - baz
